[package]
name = "biosynth"
version = "0.2.2"
edition = "2021"
authors = ["Artur Gwo≈∫dziowski <gwozdyk@gmain.com>"]
keywords = ["physics", "sandbox", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.26"
rapier2d = { version = "0.17.2", features = [ "simd-stable" ] }
egui-macroquad = "0.15.0"
egui_extras = {version = "0.21.0", features = ["image"]}
image = "0.24.6"

[build-dependencies]
embed-resource = "2.1.1"
